#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: MIT
"""
make_single_step.py — Build a single-step training-as-inference test fixture
from an existing Onnx4Deeploy `train` artifact directory, using **PyTorch
autograd** as the gradient reference (no onnxruntime-training needed).

Use case
--------
Per-tensor gradient debugging. The standard `train` test runs N optimizer
steps and compares loss at the end — when MobileNet diverges at step 2 you
cannot tell which gradient is wrong. This tool rewires the same training
graph so it can be exercised by the inference runner (deeployRunner_*.py),
which compares every graph output (loss + each <param>_grad.accumulation.out)
against a PyTorch-autograd reference and prints per-tensor errors.

Two transformations on the source directory:
  1. network.onnx        — every `tensor(bool)` graph input (lazy_reset_grad)
                           is removed and re-added as a constant initializer
                           = [True], so each InPlaceAccumulator output equals
                           the pure batch dW (no historical accum).
  2. inputs.npz / outputs.npz — regenerated by:
       a) loading initial weights from network_infer.onnx initializers,
       b) instantiating the matching PyTorch exporter,
       c) loading those weights into the PyTorch model,
       d) running a single forward + loss + backward pass with a
          deterministic random batch (seed=42),
       e) writing inputs.npz with every non-bool graph input (data, labels,
          params, grad-accumulation buffers initialized to zeros) keyed by
          input name in graph order, and outputs.npz with the loss + each
          `<param>_grad.accumulation.out` keyed by graph output name.

Usage
-----
    python3 make_single_step.py --model SimpleMLP <src_train_dir> [<dst_dir>]

If <dst_dir> is omitted, the source dir is overwritten in place.

The model name must match an entry in Onnx4Deeploy.list_available_models()
(e.g. "SimpleMLP", "DSCNN", "MobileNetV1", "ResNet8", "Autoencoder").
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

import numpy as np
import onnx
import torch
from onnx import TensorProto, numpy_helper

# Make sure we can import Onnx4Deeploy.* and onnx4deeploy.*.
HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent
sys.path.insert(0, str(PROJECT_ROOT))


GRAD_ACC_SUFFIX = "_grad.accumulation.buffer"
GRAD_OUT_SUFFIX = "_grad.accumulation.out"
GRAD_VERIFIED_SUFFIX = "_grad.verified"


def bake_inputs_as_initializers(
    onnx_path: Path,
    init_map: dict,
    labels_value: np.ndarray,
    input_shape: tuple[int, ...],
) -> tuple[list[str], list[str]]:
    """
    Bake every graph input EXCEPT the data input into ``graph.initializer``.

    Inference-runner-style single-step: only the data tensor stays as a graph
    input; labels, all parameters, all ``_grad.accumulation.buffer`` tensors,
    and any other ctrl tensors are pinned as constants. This eliminates
    `testMVP.inferMinimalType` ambiguity (zero-init grad_acc would otherwise
    infer uint8) and reduces the test fixture to a single named tensor in
    ``inputs.npz``.

    Args:
        onnx_path:    Path to the network.onnx to modify in place.
        init_map:     {param_name: ndarray} of initial weight values.
        labels_value: int64 label tensor for this single batch.
        input_shape:  Shape of the data input — used to identify the one
                      graph input that should remain.

    Returns: (data_input_name, baked_input_names).
    """
    model = onnx.load(str(onnx_path))

    data_input_name: str = ""
    kept_inputs = []
    baked: list[str] = []

    for inp in model.graph.input:
        shape = [d.dim_value for d in inp.type.tensor_type.shape.dim if d.dim_value > 0]
        etype = inp.type.tensor_type.elem_type
        # Heuristic: the data input is the float32 tensor whose shape matches
        # the model's get_input_shape(). Everything else gets baked.
        is_data = (
            etype == TensorProto.FLOAT
            and tuple(shape) == tuple(input_shape)
            and inp.name not in init_map
            and not inp.name.endswith(GRAD_ACC_SUFFIX)
        )
        if is_data and not data_input_name:
            data_input_name = inp.name
            kept_inputs.append(inp)
            continue

        # Decide the constant value to bake.
        if etype == TensorProto.INT64:
            value = labels_value
        elif etype == TensorProto.BOOL:
            # lazy_reset_grad already pinned earlier; if not, default True.
            value = np.array([True], dtype=bool)
        elif inp.name in init_map:
            value = init_map[inp.name].astype(np.float32)
        elif inp.name.endswith(GRAD_ACC_SUFFIX):
            value = np.zeros(shape, dtype=np.float32)
        else:
            value = np.zeros(shape, dtype=np.float32)

        # Reshape if necessary so the initializer matches the declared shape.
        if shape and tuple(value.shape) != tuple(shape):
            try:
                value = value.reshape(shape)
            except Exception:
                pass

        model.graph.initializer.append(numpy_helper.from_array(value, name=inp.name))
        baked.append(inp.name)

    del model.graph.input[:]
    model.graph.input.extend(kept_inputs)
    onnx.save(model, str(onnx_path))

    if not data_input_name:
        raise RuntimeError(
            "bake_inputs_as_initializers: could not identify a unique data "
            "input. Check input_shape vs graph inputs."
        )
    return data_input_name, baked


def fix_grad_output_dtypes(onnx_path: Path) -> list[str]:
    """
    Fix elem_type on each ``<param>_grad.accumulation.out`` graph output.

    ORT's training-artifact emitter sometimes declares the InPlaceAccumulator
    output as TensorProto.BOOL (elem_type=9) even though the underlying
    buffer holds float32 gradients. Deeploy/GraphSurgeon then trip on this
    mistype downstream. Force elem_type=FLOAT for every grad output so the
    deployed graph types are consistent with the kernel's actual write.

    Companion to the change at ``Tiler.py:201`` that switches the
    ``InPlaceAccumulatorV2`` binding from ``PULPInPlaceAccumulatorV2TiledBindings``
    (writes only ``accum_buffer``) to ``PULPInPlaceAccumulatorV2Bindings``
    (writes BOTH ``accum_buffer`` AND ``data_out``). With that binding the
    ``_grad.accumulation.out`` graph outputs become populated, and the test
    harness can compare them to the PyTorch-autograd reference.

    Returns the list of fixed output names.
    """
    model = onnx.load(str(onnx_path))
    fixed: list[str] = []
    for o in model.graph.output:
        if o.name.endswith(GRAD_OUT_SUFFIX):
            o.type.tensor_type.elem_type = TensorProto.FLOAT
            fixed.append(o.name)
    if fixed:
        onnx.save(model, str(onnx_path))
    return fixed


# ---------------------------------------------------------------------------
# ONNX helpers
# ---------------------------------------------------------------------------


def load_init_map(onnx_path: Path) -> dict:
    """Load all initializers from an ONNX model into {name: ndarray}."""
    model = onnx.load(str(onnx_path))
    return {init.name: numpy_helper.to_array(init) for init in model.graph.initializer}


def pin_bool_inputs(onnx_path: Path, value: bool = True) -> list[str]:
    """
    Convert every tensor(bool) graph input into a constant initializer.

    Deeploy's PULP InPlaceAccumulatorV2 binding (Bindings.py:568) expects the
    third input to be ``uint8_t``, NOT bool — Deeploy maps the ONNX bool input
    to a uint8 buffer at codegen time.  When we pin the input as a constant we
    therefore have to emit it as uint8 (= 1 byte = bool semantics) so the
    downstream binding still picks the same checker.

    Returns the list of pinned input names.
    """
    model = onnx.load(str(onnx_path))
    pinned, kept = [], []
    for inp in model.graph.input:
        if inp.type.tensor_type.elem_type == TensorProto.BOOL:
            pinned.append(inp.name)
        else:
            kept.append(inp)
    if not pinned:
        return []
    del model.graph.input[:]
    model.graph.input.extend(kept)
    for name in pinned:
        const_arr = np.array([1 if value else 0], dtype=np.uint8)
        model.graph.initializer.append(numpy_helper.from_array(const_arr, name=name))
    onnx.save(model, str(onnx_path))
    return pinned


def graph_input_specs(onnx_path: Path) -> list[tuple[str, int, list[int]]]:
    """Return (name, elem_type, shape) per graph input in declaration order."""
    model = onnx.load(str(onnx_path))
    specs = []
    for inp in model.graph.input:
        shape = [d.dim_value for d in inp.type.tensor_type.shape.dim if d.dim_value > 0]
        specs.append((inp.name, inp.type.tensor_type.elem_type, shape))
    return specs


def graph_output_names(onnx_path: Path) -> list[str]:
    model = onnx.load(str(onnx_path))
    return [o.name for o in model.graph.output]


# ---------------------------------------------------------------------------
# Exporter resolution + PyTorch-side reference computation
# ---------------------------------------------------------------------------


def resolve_exporter(model_name: str):
    """
    Look up the exporter class + config from Onnx4Deeploy.list_available_models().
    Returns an instantiated exporter with config applied.
    """
    from Onnx4Deeploy import list_available_models

    models = list_available_models()
    key = next((k for k in models if k.lower() == model_name.lower()), None)
    if key is None:
        raise ValueError(f"Unknown model '{model_name}'. Known: {sorted(models.keys())}")
    info = models[key]
    cls = info["class"]
    exporter = cls(save_path="/tmp/_unused_make_single_step")
    # Inject overrides the same way Onnx4Deeploy.py does, so create_model() picks
    # up variant / num_classes / img_size etc.
    exporter._config_overrides = dict(info.get("config", {}))
    exporter.config = exporter.load_config()
    return exporter, info


def pytorch_param_to_onnx(name: str) -> str:
    """
    Convert a PyTorch named_parameters() key to its ONNX initializer name.

    PyTorch exposes the module hierarchy with '.' (e.g. 'fc1.weight',
    'bn_stem.weight', 'blocks.0.dw.weight').  Onnx4Deeploy's exporters flatten
    it to '_' (e.g. 'fc1_weight', 'bn_stem_weight', 'blocks_0_dw_weight').
    """
    return name.replace(".", "_")


def build_pytorch_loss(model_output: torch.Tensor, labels: torch.Tensor):
    """
    Pick the loss matching the model output / labels dtypes.

    - int64 labels  → CrossEntropyLoss (logits + class indices)
    - float labels  → MSELoss          (autoencoder-style reconstruction)
    """
    if labels.dtype == torch.int64:
        return torch.nn.functional.cross_entropy(
            model_output.reshape(model_output.shape[0], -1), labels.flatten()
        )
    return torch.nn.functional.mse_loss(model_output, labels)


def load_weights_into_pytorch(model: torch.nn.Module, init_map: dict) -> list[str]:
    """
    Copy ONNX initializer values into the matching PyTorch parameters.

    Returns the list of parameter names successfully loaded.
    """
    state = model.state_dict()
    loaded = []
    for pt_name in list(state.keys()):
        onnx_name = pytorch_param_to_onnx(pt_name)
        if onnx_name not in init_map:
            continue
        pt_tensor = state[pt_name]
        np_value = init_map[onnx_name]
        # Allow shape mismatch in the leading 1-D batch_dim that ORT sometimes
        # adds; reshape strict-equal to the target.
        if pt_tensor.shape != tuple(np_value.shape):
            try:
                np_value = np_value.reshape(tuple(pt_tensor.shape))
            except Exception:
                continue
        state[pt_name] = torch.from_numpy(np.asarray(np_value, dtype=np.float32).copy())
        loaded.append(pt_name)
    model.load_state_dict(state)
    return loaded


def synthesize_inputs(
    input_shape: tuple[int, ...], num_classes: int, seed: int
) -> tuple[np.ndarray, np.ndarray]:
    """Random Gaussian input + scalar int64 label (matches Onnx4Deeploy seed=42 default)."""
    rng = np.random.default_rng(seed)
    test_input = rng.standard_normal(size=input_shape, dtype=np.float32)
    labels = np.array([rng.integers(0, max(num_classes, 2))], dtype=np.int64)
    return test_input, labels


def synthesize_mse_target(input_shape: tuple[int, ...], seed: int) -> np.ndarray:
    """Reconstruction-style float target — same shape as input."""
    rng = np.random.default_rng(seed + 1)
    return rng.standard_normal(size=input_shape, dtype=np.float32)


# ---------------------------------------------------------------------------
# Test-data regeneration (PyTorch path)
# ---------------------------------------------------------------------------


def regenerate_test_data_pytorch(
    src_dir: Path,
    model_name: str,
    seed: int = 42,
) -> None:
    """
    Build inputs.npz / outputs.npz from PyTorch autograd (no ORT/com.microsoft).

    inputs.npz: every non-bool graph input keyed by name, in graph-input order
                — data, labels, params (loaded from network_infer.onnx),
                  grad-accumulation buffers (zeros).
    outputs.npz: 'loss' + each '<param>_grad.accumulation.out' keyed by graph
                 output name. Names must match the graph-output schema, since
                 testMVP feeds them positionally and per-tensor diff reporting
                 needs the names to be intelligible.
    """
    network_path = src_dir / "network.onnx"
    infer_path = src_dir / "network_infer.onnx"

    exporter, info = resolve_exporter(model_name)
    pt_model = exporter.create_model()
    pt_model.train()  # backward needs train mode for BN/Dropout to behave consistently

    if infer_path.exists():
        # Standard path: ONNX-side init weights are authoritative; load them
        # into PyTorch so the ref grads use the same starting point that
        # Deeploy will see baked into the deployed network.
        init_map = load_init_map(infer_path)
        loaded = load_weights_into_pytorch(pt_model, init_map)
        print(
            f"   loaded {len(init_map)} initializers from network_infer.onnx; "
            f"PyTorch absorbed {len(loaded)}/{sum(1 for _ in pt_model.named_parameters())} params"
        )
    else:
        # Vendored path: only network.onnx is available (no train/infer files
        # because they were dropped before vendoring). Use PyTorch's fresh
        # random weights as the source of truth — bake the same values into
        # ONNX initializers below so Deeploy and PyTorch start from identical
        # parameters, making the per-tensor grad comparison meaningful.
        init_map = {
            pytorch_param_to_onnx(name): p.detach().cpu().numpy().astype(np.float32)
            for name, p in pt_model.named_parameters()
        }
        # Buffers (BN running stats, etc.) — PyTorch keeps them in state_dict
        # but not in named_parameters(); the ONNX graph references them as
        # graph inputs, so we need their current values too.
        for name, buf in pt_model.named_buffers():
            init_map[pytorch_param_to_onnx(name)] = buf.detach().cpu().numpy().astype(np.float32)
        print(
            f"   network_infer.onnx absent → using PyTorch fresh weights "
            f"({len(init_map)} param/buffer tensors) as ground truth"
        )

    input_shape = exporter.get_input_shape()
    # Decide loss type by inspecting graph inputs: if there is an int64 input,
    # treat it as classification labels; otherwise MSE on a synthetic target.
    in_specs = graph_input_specs(network_path)
    has_int64 = any(et == TensorProto.INT64 for _, et, _ in in_specs)
    num_classes = exporter.config.get("num_classes", 2) if exporter.config else 2

    if has_int64:
        test_input_np, labels_np = synthesize_inputs(input_shape, num_classes, seed)
        target_for_loss_np = labels_np
    else:
        test_input_np = synthesize_mse_target(input_shape, seed=seed - 1)
        labels_np = synthesize_mse_target(input_shape, seed=seed)
        target_for_loss_np = labels_np
    print(
        f"   test_input shape={test_input_np.shape}  labels shape={labels_np.shape}  "
        f"loss={'CE' if has_int64 else 'MSE'}"
    )

    # Forward + backward
    pt_input = torch.from_numpy(test_input_np)
    pt_target = torch.from_numpy(target_for_loss_np)
    pt_input.requires_grad_(False)

    pt_model.zero_grad(set_to_none=False)
    pt_output = pt_model(pt_input)
    loss = build_pytorch_loss(pt_output, pt_target)
    loss.backward()

    # Capture per-param gradients keyed by ONNX initializer name.
    pt_grads: dict[str, np.ndarray] = {}
    for pt_name, p in pt_model.named_parameters():
        if p.grad is None:
            continue
        onnx_name = pytorch_param_to_onnx(pt_name)
        pt_grads[onnx_name] = p.grad.detach().cpu().numpy().astype(np.float32)
    print(f"   captured {len(pt_grads)} PyTorch gradient tensors")

    # ── Bake every non-data graph input (labels, params, grad_accs) into
    # initializers. Inference-style fixture: only the data tensor stays as a
    # graph input.
    print(f"   Baking non-data inputs into initializers (inference-style)...")
    data_input_name, baked = bake_inputs_as_initializers(
        network_path, init_map=init_map, labels_value=labels_np, input_shape=input_shape
    )
    print(f"   data input retained: '{data_input_name}'  ({len(baked)} inputs baked)")

    # ── inputs.npz: just the one data tensor.
    saved_inputs = {data_input_name: test_input_np}
    np.savez(src_dir / "inputs.npz", **saved_inputs)
    print(f"   ✅ inputs.npz  — 1 tensor ('{data_input_name}', shape={test_input_np.shape})")

    # ── outputs.npz: graph-output-name keyed (buffer names after promotion)
    out_names = graph_output_names(network_path)
    saved_outputs: dict[str, np.ndarray] = {}
    matched_grads = 0
    for out_name in out_names:
        if out_name.endswith(GRAD_OUT_SUFFIX):
            # InPlaceAccumulator's data_out — with the non-tiled binding
            # (Tiler.py:201) this gets written with the new gradient.
            param_onnx_name = out_name[: -len(GRAD_OUT_SUFFIX)]
            if param_onnx_name in pt_grads:
                saved_outputs[out_name] = pt_grads[param_onnx_name]
                matched_grads += 1
            else:
                ref_shape = init_map.get(param_onnx_name)
                ref_shape = ref_shape.shape if ref_shape is not None else ()
                saved_outputs[out_name] = np.zeros(ref_shape, dtype=np.float32)
        elif "loss" in out_name.lower():
            saved_outputs[out_name] = np.array(loss.detach().cpu().numpy(), dtype=np.float32)
        else:
            saved_outputs[out_name] = np.zeros((), dtype=np.float32)

    np.savez(src_dir / "outputs.npz", **saved_outputs)
    print(
        f"   ✅ outputs.npz — {len(saved_outputs)} tensors "
        f"(loss + {matched_grads} grads matched to PyTorch params, "
        f"keyed by graph output names)"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert an Onnx4Deeploy train-mode artifact dir into a "
        "single-step training-as-inference test fixture, using PyTorch autograd "
        "as the gradient reference."
    )
    parser.add_argument(
        "--model",
        required=True,
        help="Onnx4Deeploy model name (e.g. SimpleMLP, DSCNN, MobileNetV1, "
        "ResNet8, Autoencoder)",
    )
    parser.add_argument("src", type=Path, help="Source train artifact directory")
    parser.add_argument(
        "dst",
        type=Path,
        nargs="?",
        default=None,
        help="Destination directory (default: in-place overwrite)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for input + label generation",
    )
    args = parser.parse_args()

    src_dir: Path = args.src
    if not (src_dir / "network.onnx").exists():
        print(f"❌ Missing network.onnx in {src_dir}", file=sys.stderr)
        return 1

    if args.dst is None:
        dst_dir = src_dir
    else:
        dst_dir = args.dst
        if dst_dir.exists():
            shutil.rmtree(dst_dir)
        shutil.copytree(src_dir, dst_dir, symlinks=False)
        print(f"📋 Copied {src_dir} → {dst_dir}")

    print(f"\n🪛 Pinning bool inputs as constants in {dst_dir}/network.onnx ...")
    pinned = pin_bool_inputs(dst_dir / "network.onnx", value=True)
    print(f"   pinned: {pinned if pinned else '(none)'}")

    print(f"\n🪛 Fixing elem_type on '_grad.accumulation.out' outputs (BOOL→FLOAT) ...")
    fixed = fix_grad_output_dtypes(dst_dir / "network.onnx")
    print(f"   fixed {len(fixed)} graph outputs to elem_type=FLOAT")

    print(f"\n🧪 Regenerating inputs.npz / outputs.npz via PyTorch autograd ...")
    regenerate_test_data_pytorch(dst_dir, model_name=args.model, seed=args.seed)

    print(f"\n✅ Single-step fixture ready: {dst_dir}")
    print("   Run with: python3 deeployRunner_siracusa.py -t <dst_dir> -p Siracusa --cores=8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
